# Nordic-darker color palette
#2e3440	user
#3b4252	dir
#434c5e	git
#4c566a	version
#5e81ac	doc (from dracula color palette)
#6272a4	time (from dracula color palette)

# some extra symbols
# 
# 

#           _     _ 
#  ______ _(_) __| |
# |_  / _` | |/ _` |
#  / / (_| | | (_| |
# /___\__,_|_|\__,_|	zaid-hassan
 
# ---------------------------------------------------------------
format = """
[░▒▓](#2e3440)\
$username\
[](bg:#3b4252 fg:#2e3440)\
$os\
$directory\
[](fg:#3b4252 bg:#434c5e)\
$git_branch\
$git_status\
[](fg:#434c5e bg:#4c566a)\
$c\
${custom.cpp}\
$python\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
${custom.sql}\
[](fg:#4c566a bg:#5e81ac)\
$docker_context\
[](fg:#5e81ac bg:#6272a4)\
$time\
$battery\
[ ](fg:#6272a4)\
\n
$cmd_duration\
$character\
"""
#add_newline = false
[battery]
disabled = false
format = '[${battery.display}](bg:#6272a4)'

[[battery.display]]
threshold = 60
style = "bg:#6272a4"

[line_break]
disabled = true

[username]
show_always = true
style_user = "bg:#2e3440"
style_root = "bg:#9A348E"
format = '[ Levisa ]($style)'
disabled = false

[os]
style = "bg:#3b4252"
disabled = false # Disabled by default

[os.symbols]
"Windows" = " 󰍲"

[directory]
style = "bg:#3b4252"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "../"
#read_only = " 󰌾"
read_only = '  READ ONLY'

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"~" = "Home"

[c]
symbol = " "
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#5e81ac"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#434c5e"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#434c5e"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:##434c5e"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[custom.cpp]
detect_extensions = ['cpp']
symbol = ""
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[custom.sql]
detect_extensions = ['sql']
symbol = ""
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
use_12hr = true
time_format = "%r" # Hour:Minute Format
style = "bg:#6272a4"
format = '[  $time ]($style)'
	
[character]
#success_symbol = '[ ➜󱞩](#6272a4)'
success_symbol = '[ 󱞪](#6272a4)'
error_symbol = '[✖](bold red)'
#style = "bg:#6272a4"

[cmd_duration]
min_time = 500
format = ' [$duration](#6272a4)'