[[language]]
name = "rust"
comment-token = "//"

[[language]]
name = "html"
formatter = { command = 'npx', args = ["prettier", "--parser", "html"] }
language-servers = [ "vscode-html-language-server" ]

[[language]]
name = "css"
formatter = { command = 'npx', args = ["prettier", "--parser", "css"] }
language-servers = [ "vscode-css-language-server", "tailwindcss-react", "emmet-ls"]

[[language]]
name = "json"
indent = { tab-width = 2, unit = "  " }
language-servers = { command = "json-languageserver", args = ["--stdio"] }
formatter = { command = "json-languageserver" , args = ["--stdin"] }

[[language]]
name = "javascript"
language-servers = [ "typescript-language-server", "tailwindcss-react", "eslint", "emmet-ls", "snippets-ls", "graphql"]
formatter = { command = 'npx', args = ["prettier", "--parser", "typescript"] }
indent = { tab-width = 4, unit = "\t" }
auto-format = true

[[language]]
name = "lua"
indent = { tab-width = 4, unit = "\t" }
auto-format = true
   
 [[language]]
name = "go"
scope = "source.go"
injection-regex = "go"
file-types = ["go"]
roots = ["Gopkg.toml", "go.mod"]
auto-format = true
comment-token = "//"
language-server = { command = "gopls" }
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "astro"
language-server = { command = "astro-ls", args = ["--stdio"]}
formatter = { command = "astro-ls", args = ["--stdin"]}

[[language]]
name = "typescript"
language-servers = [ { name = "typescript-language-server", except-features = [ "format" ] }, "efm-lsp-prettier" ]

[[language]]
name = "cpp"
